Microservices/hello/urls.py
from django.urls import path
from .views import *

app_name = "hello"

urlpatterns = [
    path('', myView, name = 'myView'),
    path('dipto/',anotherHello ,name='anotherHello'),
]

Microservices/root_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('hello.urls')),
    path('', include('todo.urls')),
]

Microservices/todo/urls.py
from django.urls import path
from .views import *

app_name = 'todo'
urlpatterns = [
    path('listView/', listView, name='listView'),
    path('addlist/', listadd, name='listadd'),
    path('deletelist/<int:list_id>/', deletelist)
]

Microservices/hello/models.py
from django.db import models

# Create your models here.

Microservices/todo/models.py
from django.db import models


class TodoItem(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
 
    def __str__(self) :
        return self.content

Microservices/hello/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def myView(request):
    return render(request, 'hello.html')

def anotherHello(request):
    return HttpResponse("<h1> This is another app </h1>")

Microservices/todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import TodoItem


def listView(request):
    all_lists = TodoItem.objects.all()
    return render(request, 'index.html', {'lists': all_lists})


def listadd(request):
    new_list = TodoItem(content=request.POST['content'])
    new_list.save()
    return HttpResponseRedirect('/listView')


def deletelist(request, list_id):
    item_del = TodoItem.objects.get(id=list_id)
    item_del.delete()
    return HttpResponseRedirect('/listView')

Microservices/hello/templates/hello.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
       <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 
    
 </head>

<h1>Microservices Django Project</h1>
<a href = "{% url 'todo:listView' %}" class = "btn btn-outline-info"> View lists </a>

{% comment %} <a href = "{% url 'update-employee' employee.id %}" class="btn btn-outline-info" > Update</a> {% endcomment %}
</html>

Microservices/todo/templates/form.html
<section class="container section">
  <form action="/addlist/" method="post">
    {% csrf_token%}
    <div class="columns">
      <div class="column is-10">
        <div class="field">
          <div class="control">
            <input class="input is-info" type="text" placeholder="Add item" name="content" id="content">
          </div>
        </div>
      </div>
      <div class="column">
        <button class="button is-primary is-fullwidth" type="submit"><i class="far fa-plus-square"></i></button>
      </div>
  </form>
</section>

Microservices/todo/templates/head.html
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container level">
      <h1 class="level-item has-text-centered title is-1">
        TASK LIST APP
      </h1>
    </div>
  </div>
</section>

Microservices/todo/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <title>TODO App</title>
</head>

<body>

  {% include 'head.html' %}
  {% include 'form.html' %}
  {% include 'list.html' %}

</body>

</html>

Microservices/todo/templates/list.html
<section class="container">
  {% for list in lists %}
  <div class="box">
    <div class="columns">
      <div class="column is-1 has-background-info">
        <span class="subtitle level-item has-text-centered is-2 h-100">{{list.id}}</span>
      </div>
      <div class="column is-9 has-background-light">
        <div class="tags has-addons">
          <span class="tag is-warning is-medium title is-5">Created</span>
          <span class="tag is-danger is-medium">{{ list.created }}</span>
        </div>
        <p class="has-text-justified">{{ list.content }}</p>
      </div>
      <div class="column is-2">
        <div class="level h-100">
          <form action="/deletelist/{{list.id}}/" method="post">
            {% csrf_token%}
            <button class="button is-danger is-fullwidth" type="submit">
              <i class="fas fa-trash-alt"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</section>